### ISSUE TITLE
Drilldown links support

### ISSUE THREAD

**Issue by fishy** [vmware/terraform-provider-wavefront#64]
Looking at the json of an existing chart with drilldown link, I think this is the key part to define it:

```json
              "chartAttributes": {
                "dashboardLinks": {
                  "*": {
                    "destination": "/dashboards/HVE",
                    "variables": {
                      "env": "env",
                      "user": "user"
                    }
                  }
                }
```

But looking at https://registry.terraform.io/providers/vmware/wavefront/latest/docs/resources/dashboard#chart-settings, I don't see how that can be defined inside `chart-settings`.

**Comment by plallin** [comment]
Hi Fishy!

I am not a contributor to this repo, just a friendly user who ran into the same issue you did.

It looks like this feature was released but not documented, see here: https://github.com/vmware/terraform-provider-wavefront/commit/b2009f6aad291d0e75f04ccefe5797d3ea6849b9

I think it's available since 2.7.2. Personally I'm using 2.8.1 and it's working perfectly.

You can uptake it in your dashboards and chart like:

```
resource "wavefront_dashboard" "test_dashboard" {
 ...
  section{
   ....

    row {
      chart {
          ....
          chart_attribute = <<EOT
                {
                "dashboardLinks": {
                  "*": {
                    "variables": {
                      "xxx": "xxx"
                    },
                    "destination": "/dashboards/xxxx"
                  }
                }
              }
              EOT
          ....
```

Formatting can be improved. Maybe there is a way to use `jsonencode` to make it easier to read. I haven't tried yet.

Best of luck!

**Comment by fishy** [comment]
@plallin that worked. thanks!

**Comment by bwinter** [comment]
Yeah, agreed, this is now supported.

I'll add a few comments to the docs so these settings are a little easier to find.
